<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventTicket.Application\EventTicket.Application.csproj" />
    <ProjectReference Include="..\EventTicket.Domain\EventTicket.Domain.csproj" />
  </ItemGroup>

</Project>
